// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvRorRHkGCR3w7iEzpeuBz-7X2j6NfYtA',
    appId: '1:753252618191:web:0d42e4c8bbe935fb2b4cba',
    messagingSenderId: '753252618191',
    projectId: 'flutterisa-3a587',
    authDomain: 'flutterisa-3a587.firebaseapp.com',
    storageBucket: 'flutterisa-3a587.appspot.com',
    measurementId: 'G-YR2BN69N1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvDOsUQdijWJ4DDGJU3zI7foIF_C8uxx4',
    appId: '1:753252618191:android:7ab6104dd96a15a22b4cba',
    messagingSenderId: '753252618191',
    projectId: 'flutterisa-3a587',
    storageBucket: 'flutterisa-3a587.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY8TlOuckCCBMRtP_b1C7XJQDMUQ0KdCU',
    appId: '1:753252618191:ios:27aca093ec081ecd2b4cba',
    messagingSenderId: '753252618191',
    projectId: 'flutterisa-3a587',
    storageBucket: 'flutterisa-3a587.appspot.com',
    iosClientId: '753252618191-rv2i5oo3c3cl77gf30mhra1r5m048i7o.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerassignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY8TlOuckCCBMRtP_b1C7XJQDMUQ0KdCU',
    appId: '1:753252618191:ios:41f005f4ef0f523f2b4cba',
    messagingSenderId: '753252618191',
    projectId: 'flutterisa-3a587',
    storageBucket: 'flutterisa-3a587.appspot.com',
    iosClientId: '753252618191-ga2dcumb8td01a52u19htl86rabnkg28.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerassignment.RunnerTests',
  );
}
